export const images = {
    heart_icon : require('../assets/images/heart_plus.png'),
    blood_bag_icon : require('../assets/images/blood_bag.png'),
    blood_drop_icon : require('../assets/images/blood_drop.png'),
    toggle_off_icon : require('../assets/images/off.png'),
    toggle_on_icon : require('../assets/images/on.png'),
    user_default_icon : require('../assets/images/user_default.png'),
    bloodgroup_icon : require('../assets/images/blood.png'),
    location_icon : require('../assets/images/location.png'),
    wave_icon:require('../assets/images/wave.png'),
    red_flag_icon:require('../assets/images/red_flag.png'),
    green_flag_icon:require('../assets/images/green_flag.png'),
    person_icon:require('../assets/images/person.png'),
    blood_d__icon:require('../assets/images/blood_d.png'),
    wireless_gif_icon:require('../assets/images/wireless.gif'),
}